blank_issues_enabled: false
contact_links:
  - name: The Discussions tab
    url: https://github.com/NanashiTheNameless/Zorin-OS-Pro/discussions/29
    about: This is where to go for general questions and support requests.
